version: '3'
services:
  app:
    image: virtualwolf/influxdb-firehose:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/service/config.json
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:8.2.0-ubuntu
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.0.8
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    command: ['--reporting-disabled']

volumes:
  influxdb:
  grafana:
