version: '3'
services:
  grafana:
    image: grafana/grafana:8.4.2-ubuntu
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.30.1
    restart: unless-stopped
    volumes:
      - ./config/telegraf.d:/etc/telegraf/telegraf.d
    command: "--config-directory /etc/telegraf/telegraf.d"
    env_file: .env
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.6.0
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    command: ['--reporting-disabled']
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8086"]
        interval: 5s
        timeout: 1s
        retries: 5

volumes:
  influxdb:
  grafana:
